import React from 'react';
import Sidebar from '../components/Sidebar';
import SavedChatTile from '../components/SavedChatTile';

const SavedChatsPage = () => {
  return (
    <div className='SavedChatsPage'>
        <Sidebar></Sidebar>
        <main>
            <h2>
              SavedChatsPage
            </h2>
            <SavedChatTile 
              dataAsked={"21/09/17"}
              question={"What is a Literature review"}
              textContent={"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et tempore consectetur animi dolorum hic impedit placeat facilis inventore veritatis est odio ipsa quis perferendis voluptas quasi, alias ratione, ad necessitatibus quam odit reiciendis corporis. Ad voluptate nam nisi velit consequatur facilis aliquam distinctio maiores iusto illum vitae ratione provident totam accusantium consequuntur blanditiis dolorem, quod explicabo. Laboriosam inventore natus maiores molestias hic obcaecati eveniet atque tempora aperiam molestiae tenetur quos provident repudiandae libero, veritatis nobis ipsum sapiente dolores accusamus. Tenetur vitae est voluptatum quod ad repellendus architecto, dicta provident, voluptate dolor molestiae at repudiandae esse odit. Voluptatibus, ex praesentium voluptas, ratione omnis adipisci laudantium nemo, obcaecati perferendis aliquid doloribus impedit quaerat ut delectus suscipit quo exercitationem tempora ducimus fugiat saepe magni mollitia molestias? Quibusdam consequatur odio praesentium sunt? Quisquam dolorem magni distinctio deleniti perferendis, eius laboriosam nulla corrupti ullam explicabo est fugit rerum incidunt, accusamus harum nemo possimus! Nostrum officia blanditiis at debitis ratione dolor sed ducimus itaque cumque repellendus voluptas placeat, dolore incidunt consectetur aliquam doloribus delectus natus sint quas beatae temporibus facere eius laborum. Amet, ex sapiente voluptas totam eos consequuntur optio. In aliquam doloremque amet consectetur minima eius deleniti tenetur assumenda eos sit. Sed quasi id quod non quo recusandae quidem ipsum accusantium unde enim repudiandae voluptatum in qui eos similique, aspernatur, quae assumenda officia! Debitis, nihil ipsum. Adipisci reprehenderit voluptate repellat numquam sequi aliquid illo veritatis ex quaerat enim perferendis iusto atque, consequuntur tempora, odio nobis accusamus nesciunt repudiandae quisquam eos porro rem ad vel corrupti? Atque fuga, inventore et ducimus quo quam quasi suscipit consectetur quos doloribus autem saepe tempore ab, laborum maxime quia, veritatis cupiditate voluptate? Accusantium quod dolorum quas? Vero eos magni voluptate itaque? Necessitatibus voluptate voluptas et quos quod debitis dolore repudiandae illo? Sint assumenda laudantium minus nostrum. Enim exercitationem possimus totam!"}
            ></SavedChatTile>
            <SavedChatTile 
              dataAsked={"21/09/17"}
              question={"What is a Literature review"}
              textContent={"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et tempore consectetur animi dolorum hic impedit placeat facilis inventore veritatis est odio ipsa quis perferendis voluptas quasi, alias ratione, ad necessitatibus quam odit reiciendis corporis. Ad voluptate nam nisi velit consequatur facilis aliquam distinctio maiores iusto illum vitae ratione provident totam accusantium consequuntur blanditiis dolorem, quod explicabo. Laboriosam inventore natus maiores molestias hic obcaecati eveniet atque tempora aperiam molestiae tenetur quos provident repudiandae libero, veritatis nobis ipsum sapiente dolores accusamus. Tenetur vitae est voluptatum quod ad repellendus architecto, dicta provident, voluptate dolor molestiae at repudiandae esse odit. Voluptatibus, ex praesentium voluptas, ratione omnis adipisci laudantium nemo, obcaecati perferendis aliquid doloribus impedit quaerat ut delectus suscipit quo exercitationem tempora ducimus fugiat saepe magni mollitia molestias? Quibusdam consequatur odio praesentium sunt? Quisquam dolorem magni distinctio deleniti perferendis, eius laboriosam nulla corrupti ullam explicabo est fugit rerum incidunt, accusamus harum nemo possimus! Nostrum officia blanditiis at debitis ratione dolor sed ducimus itaque cumque repellendus voluptas placeat, dolore incidunt consectetur aliquam doloribus delectus natus sint quas beatae temporibus facere eius laborum. Amet, ex sapiente voluptas totam eos consequuntur optio. In aliquam doloremque amet consectetur minima eius deleniti tenetur assumenda eos sit. Sed quasi id quod non quo recusandae quidem ipsum accusantium unde enim repudiandae voluptatum in qui eos similique, aspernatur, quae assumenda officia! Debitis, nihil ipsum. Adipisci reprehenderit voluptate repellat numquam sequi aliquid illo veritatis ex quaerat enim perferendis iusto atque, consequuntur tempora, odio nobis accusamus nesciunt repudiandae quisquam eos porro rem ad vel corrupti? Atque fuga, inventore et ducimus quo quam quasi suscipit consectetur quos doloribus autem saepe tempore ab, laborum maxime quia, veritatis cupiditate voluptate? Accusantium quod dolorum quas? Vero eos magni voluptate itaque? Necessitatibus voluptate voluptas et quos quod debitis dolore repudiandae illo? Sint assumenda laudantium minus nostrum. Enim exercitationem possimus totam!"}
            ></SavedChatTile>
            <SavedChatTile 
              dataAsked={"21/09/17"}
              question={"What is a Literature review"}
              textContent={"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et tempore consectetur animi dolorum hic impedit placeat facilis inventore veritatis est odio ipsa quis perferendis voluptas quasi, alias ratione, ad necessitatibus quam odit reiciendis corporis. Ad voluptate nam nisi velit consequatur facilis aliquam distinctio maiores iusto illum vitae ratione provident totam accusantium consequuntur blanditiis dolorem, quod explicabo. Laboriosam inventore natus maiores molestias hic obcaecati eveniet atque tempora aperiam molestiae tenetur quos provident repudiandae libero, veritatis nobis ipsum sapiente dolores accusamus. Tenetur vitae est voluptatum quod ad repellendus architecto, dicta provident, voluptate dolor molestiae at repudiandae esse odit. Voluptatibus, ex praesentium voluptas, ratione omnis adipisci laudantium nemo, obcaecati perferendis aliquid doloribus impedit quaerat ut delectus suscipit quo exercitationem tempora ducimus fugiat saepe magni mollitia molestias? Quibusdam consequatur odio praesentium sunt? Quisquam dolorem magni distinctio deleniti perferendis, eius laboriosam nulla corrupti ullam explicabo est fugit rerum incidunt, accusamus harum nemo possimus! Nostrum officia blanditiis at debitis ratione dolor sed ducimus itaque cumque repellendus voluptas placeat, dolore incidunt consectetur aliquam doloribus delectus natus sint quas beatae temporibus facere eius laborum. Amet, ex sapiente voluptas totam eos consequuntur optio. In aliquam doloremque amet consectetur minima eius deleniti tenetur assumenda eos sit. Sed quasi id quod non quo recusandae quidem ipsum accusantium unde enim repudiandae voluptatum in qui eos similique, aspernatur, quae assumenda officia! Debitis, nihil ipsum. Adipisci reprehenderit voluptate repellat numquam sequi aliquid illo veritatis ex quaerat enim perferendis iusto atque, consequuntur tempora, odio nobis accusamus nesciunt repudiandae quisquam eos porro rem ad vel corrupti? Atque fuga, inventore et ducimus quo quam quasi suscipit consectetur quos doloribus autem saepe tempore ab, laborum maxime quia, veritatis cupiditate voluptate? Accusantium quod dolorum quas? Vero eos magni voluptate itaque? Necessitatibus voluptate voluptas et quos quod debitis dolore repudiandae illo? Sint assumenda laudantium minus nostrum. Enim exercitationem possimus totam!"}
            ></SavedChatTile>
            <SavedChatTile 
              dataAsked={"21/09/17"}
              question={"What is a Literature review"}
              textContent={"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et tempore consectetur animi dolorum hic impedit placeat facilis inventore veritatis est odio ipsa quis perferendis voluptas quasi, alias ratione, ad necessitatibus quam odit reiciendis corporis. Ad voluptate nam nisi velit consequatur facilis aliquam distinctio maiores iusto illum vitae ratione provident totam accusantium consequuntur blanditiis dolorem, quod explicabo. Laboriosam inventore natus maiores molestias hic obcaecati eveniet atque tempora aperiam molestiae tenetur quos provident repudiandae libero, veritatis nobis ipsum sapiente dolores accusamus. Tenetur vitae est voluptatum quod ad repellendus architecto, dicta provident, voluptate dolor molestiae at repudiandae esse odit. Voluptatibus, ex praesentium voluptas, ratione omnis adipisci laudantium nemo, obcaecati perferendis aliquid doloribus impedit quaerat ut delectus suscipit quo exercitationem tempora ducimus fugiat saepe magni mollitia molestias? Quibusdam consequatur odio praesentium sunt? Quisquam dolorem magni distinctio deleniti perferendis, eius laboriosam nulla corrupti ullam explicabo est fugit rerum incidunt, accusamus harum nemo possimus! Nostrum officia blanditiis at debitis ratione dolor sed ducimus itaque cumque repellendus voluptas placeat, dolore incidunt consectetur aliquam doloribus delectus natus sint quas beatae temporibus facere eius laborum. Amet, ex sapiente voluptas totam eos consequuntur optio. In aliquam doloremque amet consectetur minima eius deleniti tenetur assumenda eos sit. Sed quasi id quod non quo recusandae quidem ipsum accusantium unde enim repudiandae voluptatum in qui eos similique, aspernatur, quae assumenda officia! Debitis, nihil ipsum. Adipisci reprehenderit voluptate repellat numquam sequi aliquid illo veritatis ex quaerat enim perferendis iusto atque, consequuntur tempora, odio nobis accusamus nesciunt repudiandae quisquam eos porro rem ad vel corrupti? Atque fuga, inventore et ducimus quo quam quasi suscipit consectetur quos doloribus autem saepe tempore ab, laborum maxime quia, veritatis cupiditate voluptate? Accusantium quod dolorum quas? Vero eos magni voluptate itaque? Necessitatibus voluptate voluptas et quos quod debitis dolore repudiandae illo? Sint assumenda laudantium minus nostrum. Enim exercitationem possimus totam!"}
            ></SavedChatTile>
            <SavedChatTile 
              dataAsked={"21/09/17"}
              question={"What is a Literature review"}
              textContent={"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et tempore consectetur animi dolorum hic impedit placeat facilis inventore veritatis est odio ipsa quis perferendis voluptas quasi, alias ratione, ad necessitatibus quam odit reiciendis corporis. Ad voluptate nam nisi velit consequatur facilis aliquam distinctio maiores iusto illum vitae ratione provident totam accusantium consequuntur blanditiis dolorem, quod explicabo. Laboriosam inventore natus maiores molestias hic obcaecati eveniet atque tempora aperiam molestiae tenetur quos provident repudiandae libero, veritatis nobis ipsum sapiente dolores accusamus. Tenetur vitae est voluptatum quod ad repellendus architecto, dicta provident, voluptate dolor molestiae at repudiandae esse odit. Voluptatibus, ex praesentium voluptas, ratione omnis adipisci laudantium nemo, obcaecati perferendis aliquid doloribus impedit quaerat ut delectus suscipit quo exercitationem tempora ducimus fugiat saepe magni mollitia molestias? Quibusdam consequatur odio praesentium sunt? Quisquam dolorem magni distinctio deleniti perferendis, eius laboriosam nulla corrupti ullam explicabo est fugit rerum incidunt, accusamus harum nemo possimus! Nostrum officia blanditiis at debitis ratione dolor sed ducimus itaque cumque repellendus voluptas placeat, dolore incidunt consectetur aliquam doloribus delectus natus sint quas beatae temporibus facere eius laborum. Amet, ex sapiente voluptas totam eos consequuntur optio. In aliquam doloremque amet consectetur minima eius deleniti tenetur assumenda eos sit. Sed quasi id quod non quo recusandae quidem ipsum accusantium unde enim repudiandae voluptatum in qui eos similique, aspernatur, quae assumenda officia! Debitis, nihil ipsum. Adipisci reprehenderit voluptate repellat numquam sequi aliquid illo veritatis ex quaerat enim perferendis iusto atque, consequuntur tempora, odio nobis accusamus nesciunt repudiandae quisquam eos porro rem ad vel corrupti? Atque fuga, inventore et ducimus quo quam quasi suscipit consectetur quos doloribus autem saepe tempore ab, laborum maxime quia, veritatis cupiditate voluptate? Accusantium quod dolorum quas? Vero eos magni voluptate itaque? Necessitatibus voluptate voluptas et quos quod debitis dolore repudiandae illo? Sint assumenda laudantium minus nostrum. Enim exercitationem possimus totam!"}
            ></SavedChatTile>

        </main>
    </div>
  )
}

export default SavedChatsPage


